title: Pakshal Bohra
baseurl: ""
url: "https://pakshal23.github.io"

theme: minima
plugins:
  - jekyll-sitemap

permalink: /blog/:slug/

kramdown:
  math_engine: mathjax

header_pages:
  - cv.md
  - research.md
  - teaching.md
  - blog.md
